FROM node:20-alpine AS build
WORKDIR /build
COPY frontend/ .
RUN npm ci
RUN npm run build

FROM nginx:alpine
COPY --from=build /build/dist/cb-ild-frontend /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
